Presentation/Controllers/BooksController.cs
using Microsoft.AspNetCore.Mvc;
using Domain.Interfaces;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using Persistance;
using Domain.Entities;
using Microsoft.AspNetCore.Identity;
using Domain.Models;
using System;

namespace Presentation.Controllers
{
    public class BooksController : Controller
    {
        private IBookRepository _bookRepository;
        private DatabaseContext _db;
        private readonly UserManager<User> _userManager;


        public BooksController(IBookRepository bookRepository,UserManager<User> userManager, DatabaseContext db)
        {
            _bookRepository = bookRepository;
            _userManager = userManager;
            _db = db;

        }

        public IActionResult ThrillerBooks()
        {
            return View(_bookRepository.TypeBooks("Thriller"));
        }

        public IActionResult RomanceBooks()
        {
            return View(_bookRepository.TypeBooks("Romance"));
        }


        public IActionResult DramaBooks()
        {
            return View(_bookRepository.TypeBooks("Drama"));

        }


        public IActionResult ActionBooks()
        {
            return View(_bookRepository.TypeBooks("Action"));
        }

     
        [Authorize]
        public IActionResult AddBook()
        {
            return View();
        }


        [HttpPost]
        public IActionResult AddBook(CreateBookModel model)
        {

            if(ModelState.IsValid)
            {
                _bookRepository.AddBook(model);
            }

            return RedirectToAction("Index", "Home");

        }

/*

        [HttpPost]
        public IActionResult AddBook(CreateBookModel model)
        {

            if(ModelState.IsValid)
            {

                Book book = Book.Create(model.Name, model.Type, model.Author, model.Path, model.PhotoPath, model.Description,DateTime.Now);
                _bookRepository.AddBook(book);
            }

            return RedirectToAction("Index", "Home");

        }
        */


 
        public IActionResult Download(string name)
        {
            
            var idUser = _userManager.GetUserId(User);
            var user = _db.Users.Find(idUser);
            _bookRepository.AddBookToDownload(user, name);
           
            string fileName = name + ".pdf";
            string fullName ="Books/" + fileName;
            byte[] fileBytes = GetFile(fullName);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);

        }

        byte[] GetFile(string s)
        {
            FileStream fs = System.IO.File.OpenRead(s);
            byte[] data = new byte[fs.Length];
            int br = fs.Read(data, 0, data.Length);
            if (br != fs.Length)
            {
                throw new IOException(s);
            }
            return data;
        }


        public ActionResult ReadPdf(string name)
        {
            string path = "Books/" + name + ".pdf";
            string fileName = name + ".pdf";
            var fileStream = new FileStream(path,FileMode.Open,FileAccess.Read);
            var fsResult = new FileStreamResult(fileStream, "application/pdf");
            return fsResult;

        }

        public JsonResult AddToReadBooks(string id)
        {

            var idUser = _userManager.GetUserId(User);
            var user = _db.Users.Find(idUser);
            string result= _bookRepository.AddBookToReadUser(user, id);
            return Json(new { isAdded = result });
        

        }

        public IActionResult SeeAddedBooks()
        {
            var idUser = _userManager.GetUserId(User);
            var model=_bookRepository.SeeAddedBooks(idUser);

            return View(model);
        } 

        public IActionResult SeeRecommendations()
        {
           
            var idUser = _userManager.GetUserId(User);
            var user = _db.Users.Find(idUser);
            var model= _bookRepository.RecommendBooks(user);
            if (model.error != null)
            {
                TempData["errorRecommend"] = model.error;
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View(model);
            }
        }

    }
}

Presentation/Controllers/HomeController.cs
using System.Linq;
using Domain.Entities;
using Domain.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Persistance;
using Domain.Models;


namespace Presentation.Controllers
{

    public class HomeController : Controller
    {
        private IBookRepository _bookRepository;
        private DatabaseContext _db;
        private readonly UserManager<User> _userManager;

        public HomeController(IBookRepository bookRepository,DatabaseContext db,UserManager<User> userManager)
        {
            _bookRepository = bookRepository;
            _db = db;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var idUser = _userManager.GetUserId(User);
            var currentUser = _db.Users.Find(idUser);

            int totalBooksToReadUser = _bookRepository.BooksToReadPerUser(idUser);
            int totalBooks = _bookRepository.GetAllBooks().Count();
            int booksDownloaded = _bookRepository.NrBooksDownloaded(currentUser);
            var topBooks = _bookRepository.TopBooks(6);
            var latesteBooks = _bookRepository.LatesteBooks(3);


            var model = new HomePageModel { BooksToReadNumber = totalBooksToReadUser, AllBooksNumber = totalBooks, BooksDownloaded=booksDownloaded,TopBooks = topBooks.ToList(),LatestBooks=latesteBooks.ToList() };

            return View(model);
        }
    }
}

Presentation/Controllers/RatingController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Domain.Entities;
using Domain.Models;
using Persistance;
using Domain.Interfaces;
using System.Diagnostics.Contracts;


namespace Presentation.Controllers
{
    public class RatingController:Controller
    {
        private readonly UserManager<User> _userManager;
        private DatabaseContext _db;
        private IRatingRepository _ratingRepository;



        public RatingController( UserManager<User> userManager, DatabaseContext db,IRatingRepository ratingRepository)
        {
            _userManager = userManager;
            _ratingRepository = ratingRepository;
            _db = db;
        }


        //se apeleaza inainte de seeRatings
        public IActionResult UpdateBook(string id)
        {
            TempData["Book"] = id;
            return RedirectToAction("SeeRatings");

        }


        public IActionResult SeeRatings()
        {
            string id = (string)TempData["Book"];
            var model=_ratingRepository.GetRatingsByBookId(id);
            return View(model);

        }

     
        [HttpPost]
        public IActionResult AddRatings(SeeReviewModel model)
        {
            Contract.Ensures(Contract.Result<IActionResult>() != null);
            if (ModelState.IsValid)
            {
                var idUser = _userManager.GetUserId(User);
                var user = _db.Users.Find(idUser);
               
                if(_ratingRepository.AddRating(user,model)==false)
                {

                    TempData["error"] = "You already added a comment";
                }
                return RedirectToAction("UpdateBook", new { id = model.Book.BookId });
            }
            return RedirectToAction("UpdateBook", new { id = model.Book.BookId });


        }
      
    }

}

Presentation/Views/Home/Index.cshtml
@model HomePageModel


<section id="options">
    <div class="container">
        <h2 class="sectionHeading"><span class="subHeading">What we do</span>
            Your Options
        </h2>
        <p class="sectionDesc">Gone are the days when you had to struggle in order to find a book .With us you can read anytime your favorite e-books with no added cost or if you can not find it in our library just make a request and we will look into it.</p>
        <div class="sectionContent">
            <div class="row hoverEffect">

            <div class="col-md-4 col-sm-4">
                    <div class="item">
                        <a class="overlay" asp-area="" asp-controller="Books" asp-action="SeeRecommendations">
                            <span class="content">
                                <i class="fa fa-book"></i>
                                Recommendations
                            </span>
                            <img src="../images/user account/img1.jpg" alt="">
                        </a>
                    </div>
                </div>


            <div class="col-md-4 col-sm-4">
                    <div class="item">
                        <a class="overlay" asp-area="" asp-controller="Books" asp-action="SeeAddedBooks">
                            <span class="content">
                                <i class="fa fa-bookmark"></i>
                                To download
                            </span>
                            <img src="../images/user account/img2.jpg" alt="">
                        </a>
                    </div>
                </div>

            <div class="col-md-4 col-sm-4">
                    <div class="item">
                        <a class="overlay" asp-area="" asp-controller="Books" asp-action="AddBook">
                            <span class="content">
                                <i class="fa fa-book"></i>
                                Add book
                            </span>
                            <img src="../images/user account/imagine3.jpg" alt="">
                        </a>
                    </div>
            </div>


            
            
            </div>
        </div>
    </div> 
</section>



<section id="counting">
    <div class="container">
        <div layout="row" class="verticalStretch">

           <div class="item">
                <div class="number">@Model.AllBooksNumber</div>
                <div class="text">Books</div>
            </div>

            <div class="item">
                <div class="number">@Model.BooksDownloaded</div>
                <div class="text">Downloaded books</div>
            </div>

            <div class="item">
                <div class="number"> @Model.BooksToReadNumber</div>
                <div class="text">Books to read</div>
             </div>
    </div>
    </div>
</section>




<section id="books" style="margin-bottom:-100px;">
    <div class="container">
        <h2 class="sectionHeading">
            <span class="subHeading">Books</span>
            Top 6 best rated books
        </h2>
        <div class="sectionContent">
            
   

@{
                int counter=0;

                foreach (var b in Model.TopBooks)
{

                 if (counter%3==0)
                {
                     @:<div class="row hoverEffect"> 
                }
                    
                <div class="col-md-4 col-sm-4">
                    <div class="item">
                        <div class="overlay" href="#">
                            <div class="content">
                                

                             <div class="point-of-reference">
                                <div class="imgwrap">
                                <button  class="icon" style="color: white;background: transparent;padding: 0;border: none;" onclick="DownloadBook('@b.Name')" ><i class="mdi fa fa-download"></i></button>
                                <div class="rollover">
                                        <div class="roll-inner">
                                        <div class="roll-content">
                                                <p>Download</p>
                                        </div>
                                        </div>
                                        </div>
                                        </div>
                                        </div>

                             <div class="point-of-reference">
                                <div class="imgwrap">
                                <button  class="icon" style="color: white;background: transparent;padding: 0;border: none;" onclick="seeBook('@b.BookId')" ><i class="mdi fa fa-book"></i></button>
                                <div class="rollover">
                                        <div class="roll-inner">
                                        <div class="roll-content">
                                            <p>Description</p>
                                        </div>
                                        </div>
                                        </div>
                                        </div>
                                        </div>

                                <div class="point-of-reference">
                                    <div class="imgwrap">
                                        <button class="icon" formtarget="_blank" style="color: white;background: transparent;padding: 0;border: none;" onclick="ReadBook('@b.Name')"><i class="mdi fa fa-file-pdf-o"></i></button>
                                        <div class="rollover">
                                            <div class="roll-inner">
                                                <div class="roll-content">
                                                    <p>Read now</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                                <div class="point-of-reference">
                                    <div class="imgwrap">
                                        <button class="icon" style="color: white;background: transparent;padding: 0;border: none;" onclick="AddToReadBooks('@b.BookId')" ><i class="mdi fa fa-bookmark"></i></button>
                                        <div class="rollover">
                                            <div class="roll-inner">
                                                <div class="roll-content">
                                                    <p>Download later</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>

                            <div class="articleThumb">
                            <img src= "@b.PhotoPath">
                             <div class="date">
                                    <span class="number">@b.Score</span>
                                    <span class="text">Stars</span>
                              </div>
                              </div>
                            
                        </div>
                    </div>
                    <div class="info">
                        <h4 class="name">@b.Name </h4>
                        <span class="regency">by @b.Author  / @b.Type</span>

                    </div>
                </div>
         if(counter%3==2)
        {
             @:</div>
        }
       counter++;

}
}
    </div>
    </div>
</section>  


<section id="books" style="margin-bottom:-100px;">
    <div class="container">
        <h2 class="sectionHeading">
            <span class="subHeading">Books</span>
            Latest Books
        </h2>
        <div class="sectionContent">
            <div class="row hoverEffect">
   

            
@foreach (var b in Model.LatestBooks)
{
                 <div class="col-md-4 col-sm-4">
                    <div class="item">
                        <div class="overlay" href="#">
                            <div class="content">
                                

                             <div class="point-of-reference">
                                <div class="imgwrap">
                                <button  class="icon" style="color: white;background: transparent;padding: 0;border: none;" onclick="DownloadBook('@b.Name')" ><i class="mdi fa fa-download"></i></button>
                                <div class="rollover">
                                        <div class="roll-inner">
                                        <div class="roll-content">
                                                <p>Download</p>
                                        </div>
                                        </div>
                                        </div>
                                        </div>
                                        </div>

                             <div class="point-of-reference">
                                <div class="imgwrap">
                                <button  class="icon" style="color: white;background: transparent;padding: 0;border: none;" onclick="seeBook('@b.BookId')" ><i class="mdi fa fa-book"></i></button>
                                <div class="rollover">
                                        <div class="roll-inner">
                                        <div class="roll-content">
                                            <p>Description</p>
                                        </div>
                                        </div>
                                        </div>
                                        </div>
                                        </div>

                                <div class="point-of-reference">
                                    <div class="imgwrap">
                                        <button class="icon" formtarget="_blank" style="color: white;background: transparent;padding: 0;border: none;" onclick="ReadBook('@b.Name')"><i class="mdi fa fa-file-pdf-o"></i></button>
                                        <div class="rollover">
                                            <div class="roll-inner">
                                                <div class="roll-content">
                                                    <p>Read now </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                                <div class="point-of-reference">
                                    <div class="imgwrap">
                                        <button class="icon" style="color: white;background: transparent;padding: 0;border: none;" onclick="AddToReadBooks('@b.BookId')" ><i class="mdi fa fa-bookmark"></i></button>
                                        <div class="rollover">
                                            <div class="roll-inner">
                                                <div class="roll-content">
                                                    <p>Download later</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>

                            <div class="articleThumb">
                            <img src= "@b.PhotoPath">
                             <div class="date">
                                    <span class="number">@b.Added.Day</span>
                                    <span class="text">@b.Added.ToString("MMM")</span>
                              </div>
                              </div>
                            
                        </div>
                    </div>
                    <div class="info">
                        <h4 class="name">@b.Name </h4>
                        <span class="regency">by @b.Author  / @b.Type</span>

                    </div>
                </div>
}

  
    </div>
    </div>
    </div>
</section>  

@if (TempData["errorRecommend"]!=null)
{
<script type="text/javascript">
window.onload = function(){
    alert("Download at least one book in order to see recommendations");
}
</script>
}

<script>

 function AddToReadBooks(Id)
    {
        var values={id:Id};
        $.post("/Books/AddToReadBooks", values, function (result)
        {  
            alert(result.isAdded);
           
    });
    }

     function seeBook(id)
    {
        location.href = '@Url.Action("UpdateBook", "Rating" , new {id = "ID"})'.replace("ID",id);

    }


    function DownloadBook(_name)
    {
        location.href = '@Url.Action("Download", "Books" , new {name = "_name"})'.replace("_name",_name);
    }


    function ReadBook(_name)
    {
        location.href = '@Url.Action("ReadPdf", "Books" , new {name = "_name"})'.replace("_name",_name);
    }

</script>